[project]
name = "memory-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "jinja2>=3.1.6",
    "pandas>=2.3.3",
    "plotly>=6.4.0",
]
